# Generated by Django 4.1.4 on 2022-12-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='size',
            field=models.IntegerField(choices=[(1, '小'), (2, '中'), (3, '大')], default=2, verbose_name='規模'),
        ),
    ]
