# Generated by Django 4.1.4 on 2022-12-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_company_shop_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='りんご名')),
                ('shops', models.ManyToManyField(to='shop.shop', verbose_name='店')),
            ],
        ),
    ]
